### ISSUE TITLE
[feat] CJS

### ISSUE THREAD

**Issue by loynoir** [sindresorhus/make-synchronous#11]
https://github.com/sindresorhus/make-synchronous#make-synchronous

> This is the wrong tool for most tasks! Prefer using async APIs whenever possible.

- This is not a generic purpose package
- under the philosophy of special handling for special case

So, I think it might be better to have commonjs version of this package.

I think there are still a lot of real world cases need `make-synchronous` within CJS context, for example
- CJS package load ESM only package
- https://github.com/eslint/eslint/issues/15394
- ...

So, as this is not a generic purpose package, I think it's worth to get CJS back.
- dual package
- or conditional exports
- or backport

BTW, what are the real world use case of `make-synchronous` within ESM context?

**Comment by sindresorhus** [comment]
I have no plans for CommonJS support.
