### ISSUE TITLE
Why not sleep-synchronously until the async call is done?

### ISSUE THREAD

**Issue by papb** [sindresorhus/make-synchronous#3]
Why not [sleep-synchronously](https://github.com/sindresorhus/sleep-synchronously) until the async call is done?

Something like

```js
const sleepSynchronously = require('sleep-synchronously');

function makeSynchronous(fn) {
  let done = false;
  let _result;
  let _error;

  (async () => {
    try {
      _result = await fn();
    } catch (error) {
      _error = error;
    }
    done = true;
  })();

  while (!done) {
    sleepSynchronously(100);
  }

  if (_error) {
    throw _error;
  }

  return _result;
}
```

**Comment by sindresorhus** [comment]
I made this package before I realized something like `sleep-synchronously` was possible. When I had it, I thought about this implementation too, but couldn't get it working right away and decided to ship it as is just to get it out.

I tried the following now and it just hangs forever after printing `a`:

```js
const sleepSynchronously = require('sleep-synchronously');

function makeSynchronous(fn) {
  let done = false;
  let _result;
  let _error;

  (async () => {
    try {
      _result = await fn();
    } catch (error) {
      _error = error;
    }
    done = true;
  })();

  while (!done) {
    sleepSynchronously(100);
  }

  if (_error) {
    throw _error;
  }

  return _result;
}

let x = makeSynchronous(async () => {
  console.log('a');
  await require('delay')(100);
  console.log('b');
});

console.log('1');
x();
console.log('2');
```

**Comment by Richienb** [comment]
This is **impossible**. Asynchronous code always waits for synchronous code to finish before executing. However, idle time is never reached because the synchronous sleep is continuously restarted.
