### ISSUE TITLE
Passing parameter to first async call produces "No debugger available, can not send 'variables'"

### ISSUE THREAD

**Issue by berndnoll** [sindresorhus/make-synchronous#6]
I am calling an async function that calls a series of async functions.
First call in the series gives me the error "No debugger available...".
(createConnection)

Code:

function syncFunction(param) {
	const ms = require('make-synchronous');
	const fn = ms(a.asyncFunction(param))
	return fn(param)
}

async function asyncFunction(param) {
  var rows = []
  const mariadb = require('mariadb');
  var conn = await mariadb.createConnection({host: 'localhost', user: 'rudi', password:'***'});
  try {
	rows = await conn.query("SELECT 1 as val");
  } catch (err) {
	  console.log('error')
	throw err;
  } finally {
	await conn.destroy()
}
  console.log(rows)
  return rows
}

var res = syncFunction('example')
console.log(res)

Here is the output

[stdin]:15
                                        const result = await ([object Promise])(...arguments_);
                                                                      ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:207:5)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
end
[
  { val: 1 },
  meta: [
    ColumnDef {
      _parse: [StringParser],
      collation: [Collation],
      columnLength: 1,
      columnType: 3,
      flags: 129,
      scale: 0,
      type: 'LONG'
    }
  ]
]

**Comment by berndnoll** [comment]
<img width="402" alt="2021-05-06 19_58_55-● a js - mariadb - Visual Studio Code" src="https://user-images.githubusercontent.com/65687281/117379472-8e968c80-aea5-11eb-982a-fb6fc28482a1.png">

**Comment by sindresorhus** [comment]
```diff
-const fn = ms(a.asyncFunction(param))
+const fn = ms(a.asyncFunction)
```
