### ISSUE TITLE
Can't execute mariadb function wrapper

### ISSUE THREAD

**Issue by berndnoll** [sindresorhus/make-synchronous#7]
I am trying to build a wrapper around a mariadb function, but calling it fails with error:
What am I doing wrong?

S:\Development\mariadb\node_modules\make-synchronous\index.js:61
                        throw error;
                        ^

ReferenceError: ConnOptions is not defined
    at createConnection ([stdin]:17:21)
    at [stdin]:22:3
    at [stdin]:27:6
    at Script.runInThisContext (vm.js:120:18)
    at Object.runInThisContext (vm.js:309:38)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:207:5)

Code:

const ms = require('make-synchronous');
const mariadb = require('mariadb');

function createConnection(opts) {
    const fn = ms(mariadb.createConnection)
    var conn = fn(opts)
    return conn
}

var conn = createConnection({host:'localhost',user:'rudi',password:'secret'})

**Comment by sindresorhus** [comment]
You need to read the docs.

> The given function is executed in a subprocess, so you cannot use any variables/imports from outside the scope of the function. You can pass in arguments to the function. To import dependencies, use either require(…) or await import(…) in the function body.

**Comment by berndnoll** [comment]
Hi, thanks for the feedback. So I get it, you can't pass any objects to it.
However, I changed it to passing simple arguments and now the spawnSync call never gets back. 
No output, no error message. Thoughts?

Code:
  function createConnection(opts) {
	const ms = require('make-synchronous');
	const fn = ms(a.createConn)
	  var conn = fn(opts.host,opts.user,opts.password,opts.port, opts.database)
	  return conn
  }

Code from a.js:
  async function createConn(host, user, password, port, db) {
	const mariadb = require('mariadb');
	var conn = await mariadb.createConnection({host:host,user:user,password:password,port:port,database:db})
	return conn
  }
